railsmytest1/config/routes.rb
Rails.application.routes.draw do
  resources :mynote_texts
  get 'books/foo'

  get 'books/foo_res'
  post 'books/foo_res'

  get 'books/bar'

  get 'books/bar_res'

  get 'books/baz'

  get 'books/baz_res'

  get 'mynotes/hoge'

  get 'mynotes/hoge_res'
  post 'mynotes/hoge_res'

  get 'mynotes/fuga'

  get 'mynotes/fuga_res'

  get 'mynotes/piyo'

  get 'mynotes/piyo_res'

  resources :posts

end

railsmytest1/app/models/mynote_text.rb
class MynoteText < ActiveRecord::Base
end

railsmytest1/app/models/post.rb
class Post < ActiveRecord::Base
end

railsmytest1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

railsmytest1/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def foo
    @search = BooksText.new
  end

  def foo_res
    @search = BooksText.new(params.require(:books_text).permit(:keyword1, :keyword2))

    if @search.valid?
      render plain: '[' + @search.keyword1 + '][' + @search.keyword2 + ']'
    else
      render plain: @search.errors.full_messages[0]
    end
  end

  def bar
  end

  def bar_res
  end

  def baz
  end

  def baz_res
  end
end

railsmytest1/app/controllers/books_text.rb
class BooksText
  include ActiveModel::Model

  attr_accessor :keyword1, :keyword2

  validates :keyword1, presence: true

end

railsmytest1/app/controllers/mynote_texts_controller.rb
class MynoteTextsController < ApplicationController
  before_action :set_mynote_text, only: [:show, :edit, :update, :destroy]

  # GET /mynote_texts
  # GET /mynote_texts.json
  def index
    @mynote_texts = MynoteText.all
  end

  # GET /mynote_texts/1
  # GET /mynote_texts/1.json
  def show
  end

  # GET /mynote_texts/new
  def new
    @mynote_text = MynoteText.new
  end

  # GET /mynote_texts/1/edit
  def edit
  end

  # POST /mynote_texts
  # POST /mynote_texts.json
  def create
    @mynote_text = MynoteText.new(mynote_text_params)

    respond_to do |format|
      if @mynote_text.save
        format.html { redirect_to @mynote_text, notice: 'Mynote text was successfully created.' }
        format.json { render :show, status: :created, location: @mynote_text }
      else
        format.html { render :new }
        format.json { render json: @mynote_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mynote_texts/1
  # PATCH/PUT /mynote_texts/1.json
  def update
    respond_to do |format|
      if @mynote_text.update(mynote_text_params)
        format.html { redirect_to @mynote_text, notice: 'Mynote text was successfully updated.' }
        format.json { render :show, status: :ok, location: @mynote_text }
      else
        format.html { render :edit }
        format.json { render json: @mynote_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mynote_texts/1
  # DELETE /mynote_texts/1.json
  def destroy
    @mynote_text.destroy
    respond_to do |format|
      format.html { redirect_to mynote_texts_url, notice: 'Mynote text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mynote_text
      @mynote_text = MynoteText.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mynote_text_params
      params.require(:mynote_text).permit(:keyword1, :keyword2)
    end
end

railsmytest1/app/controllers/mynotes_controller.rb
class MynotesController < ApplicationController
  def hoge
    @search = MynotesText.new
  end

  def hoge_res
    @search = MynotesText.new(params.require(:mynotes_text).permit(:keyword1, :keyword2))

    if @search.valid?
      render plain: '[' + @search.keyword1 + '][' + @search.keyword2 + ']'
    else
      render plain: @search.errors.full_messages[0]
    end
  end

  def fuga
  end

  def fuga_res
  end

  def piyo
  end

  def piyo_res
  end
end

railsmytest1/app/controllers/mynotes_text.rb
class MynotesText
  include ActiveModel::Model

  attr_accessor :keyword1, :keyword2

  validates :keyword1, presence: true

end

railsmytest1/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

railsmytest1/app/helpers/application_helper.rb
module ApplicationHelper
end

railsmytest1/app/helpers/books_helper.rb
module BooksHelper
end

railsmytest1/app/helpers/mynote_texts_helper.rb
module MynoteTextsHelper
end

railsmytest1/app/helpers/mynotes_helper.rb
module MynotesHelper
end

railsmytest1/app/helpers/posts_helper.rb
module PostsHelper
end

railsmytest1/app/views/books/bar.html.erb
<h1>Books#bar</h1>
<p>Find me in app/views/books/bar.html.erb</p>

railsmytest1/app/views/books/bar_res.html.erb
<h1>Books#bar_res</h1>
<p>Find me in app/views/books/bar_res.html.erb</p>

railsmytest1/app/views/books/baz.html.erb
<h1>Books#baz</h1>
<p>Find me in app/views/books/baz.html.erb</p>

railsmytest1/app/views/books/baz_res.html.erb
<h1>Books#baz_res</h1>
<p>Find me in app/views/books/baz_res.html.erb</p>

railsmytest1/app/views/books/foo.html.erb
<h1>Books#foo</h1>
<p>Find me in app/views/books/foo.html.erb</p>

<%= form_for @search, url: {action: :foo_res} do |f| %>
    <%= f.text_field :keyword1, size:20 %>
    <%= f.text_field :keyword2, size:50 %>
    <%= f.submit '検索' %>
<% end %>

railsmytest1/app/views/books/foo_res.html.erb
<h1>Books#foo_res</h1>
<p>Find me in app/views/books/foo_res.html.erb</p>

railsmytest1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsmytest1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

railsmytest1/app/views/mynote_texts/_form.html.erb
<%= simple_form_for(@mynote_text) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% # summernote %>
    <%= f.input :keyword1, as: :summernote %>
    <%= f.input :keyword2, as: :summernote  %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

railsmytest1/app/views/mynote_texts/edit.html.erb
<h1>Editing Mynote Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @mynote_text %> |
<%= link_to 'Back', mynote_texts_path %>

railsmytest1/app/views/mynote_texts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Mynote Texts</h1>

<table>
  <thead>
    <tr>
      <th>Keyword1</th>
      <th>Keyword2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mynote_texts.each do |mynote_text| %>
      <tr>
        <td><%= mynote_text.keyword1 %></td>
        <td><%= mynote_text.keyword2 %></td>
        <td><%= link_to 'Show', mynote_text %></td>
        <td><%= link_to 'Edit', edit_mynote_text_path(mynote_text) %></td>
        <td><%= link_to 'Destroy', mynote_text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mynote text', new_mynote_text_path %>

railsmytest1/app/views/mynote_texts/new.html.erb
<h1>New Mynote Text</h1>

<%= render 'form' %>

<%= link_to 'Back', mynote_texts_path %>

railsmytest1/app/views/mynote_texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword1:</strong>
  <%= @mynote_text.keyword1 %>
</p>

<p>
  <strong>Keyword2:</strong>
  <%= @mynote_text.keyword2 %>
</p>

<%= link_to 'Edit', edit_mynote_text_path(@mynote_text) %> |
<%= link_to 'Back', mynote_texts_path %>

railsmytest1/app/views/mynotes/fuga.html.erb
<h1>Mynotes#fuga</h1>
<p>Find me in app/views/mynotes/fuga.html.erb</p>

railsmytest1/app/views/mynotes/fuga_res.html.erb
<h1>Mynotes#fuga_res</h1>
<p>Find me in app/views/mynotes/fuga_res.html.erb</p>

railsmytest1/app/views/mynotes/hoge.html.erb
<h1>Mynotes#hoge</h1>
<p>Find me in app/views/mynotes/hoge.html.erb</p>

<%= simple_form_for(@search, url: {action: :hoge_res}) do |f| %>
    <%= f.error_notification %>

    <div class="form-group">
      <%= f.input :keyword1, input_html:{class:'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.input :keyword2, class:'summernote' %>
    </div>

    <div class="form-group">
      <%= f.button :submit, class:'btn btn-default' %>
    </div>
<% end %>

<%# original >> %>
<% if false %>
<%= form_for @search, url: {action: :hoge_res} do |f| %>
    <%= f.text_field :keyword1, size:20 %>
    <%= f.text_field :keyword2, size:50 %>
    <%= f.submit '検索' %>
<% end %>
<% end %>

railsmytest1/app/views/mynotes/hoge_res.html.erb
<h1>Mynotes#hoge_res</h1>
<p>Find me in app/views/mynotes/hoge_res.html.erb</p>

railsmytest1/app/views/mynotes/piyo.html.erb
<h1>Mynotes#piyo</h1>
<p>Find me in app/views/mynotes/piyo.html.erb</p>

railsmytest1/app/views/mynotes/piyo_res.html.erb
<h1>Mynotes#piyo_res</h1>
<p>Find me in app/views/mynotes/piyo_res.html.erb</p>

railsmytest1/app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
    <%= f.error_notification %>

    <div class="form-group">
      <%= f.input :title, input_html:{class:'form-control'} %>
    </div>
    <div class="form-group">
      <%= f.input :content, class:'summernote' %>
    </div>

    <div class="form-group">
      <%= f.button :submit, class:'btn btn-default' %>
    </div>
<% end %>


<%# original >> %>
<% if false %>
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% end %>

railsmytest1/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

railsmytest1/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

railsmytest1/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

railsmytest1/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>